### ISSUE TITLE
Define Entity ManagerAccess

### ISSUE THREAD

**Issue by francis-pouatcha** [ADORSYS-GIS/ledgers#19]
#### Overview:
`ManagerAccess` is an essential entity in the bank account access management model, responsible for managing access to the account. This role grants specific individuals or entities (typically managers within an organization or a legal representative) the ability to manage permissions and access levels for other users. While the `ManagerAccess` entity allows for extensive control over who can interact with the account, it may not grant direct operational control over the account itself, depending on the defined permissions.

#### Key Characteristics:

1. **Access Control Management:**
   - The primary responsibility of users with `ManagerAccess` is to manage the roles and permissions of other individuals or entities that require access to the account.
   - They can create, modify, or revoke access for roles such as `AgentAccess`, `AuditorAccess`, and `PoAAccess`, ensuring that the appropriate users have the required level of access.
   - `ManagerAccess` users typically operate within the scope defined by the `SeniorManagerAccess`, who oversees their actions.

2. **Delegated Access:**
   - Users with `ManagerAccess` are delegated authority by a `SeniorManagerAccess` user.
   - They are entrusted to ensure that access is distributed according to organizational needs or individual permissions.
   - While they can manage access, their own permissions may not extend to executing transactions or viewing sensitive account information unless explicitly allowed.

3. **Permission Management:**
   - `ManagerAccess` users have the capability to:
     - Grant access to other roles like `AgentAccess`, `AuditorAccess`, or create new access based on Power of Attorney (`PoAAccess`).
     - Modify the scope of access for existing users, adjusting their permissions based on the organization's needs or the account holder's instructions.
     - Revoke or suspend access for individuals no longer needing it (e.g., employees leaving an organization or partners completing their duties).
   - These actions help ensure a secure and flexible management system for account access.

4. **Operational Limitations:**
   - Although `ManagerAccess` is primarily focused on managing access permissions, the user with this role may have restricted direct interaction with the account, depending on the access configuration.
   - Direct operational tasks, such as transferring funds, viewing the full account balance, or approving payments, are typically not granted unless the `scope` of the manager's access includes these permissions.
   - The `scope` field of the `ManagerAccess` entity allows fine-grained control over what a manager can or cannot do.

5. **Scope of Permissions:**
   - The `scope` field defines the specific actions the `ManagerAccess` user is permitted to perform. These may include:
     - **Manage Access:** The ability to add, modify, or remove access for other users.
     - **View Account Details:** Optional permission allowing the manager to view the account's balance or transaction history, depending on their role.
     - **Execute Transactions:** In certain cases, the manager might be allowed to approve or initiate transactions, but this is typically reserved for more trusted or senior roles.
   - The `scope` is critical for customizing each manager's responsibilities and ensuring that no excess permissions are granted.

6. **Weight:**
   - The `weight` attribute determines the extent of control a `ManagerAccess` user has. For instance:
     - A manager with a weight of **1** might have full authority to manage access and even perform operational tasks (if allowed by scope).
     - A manager with a lower weight (e.g., **0.5**) may only have partial control, such as managing access but not viewing sensitive account details or making transactions.
   - This allows for flexible delegation of duties based on seniority or organizational structure.

7. **Status:**
   - Like other access entities, `ManagerAccess` can have different statuses:
     - **Active:** The manager can fully perform their role as defined by their access scope.
     - **Restricted:** The manager's permissions might be temporarily reduced, limiting their ability to add or remove access (e.g., during an internal audit).
     - **Suspended:** The manager can no longer manage access, typically due to role changes or security concerns.
   - The status ensures that `ManagerAccess` can be dynamically adjusted based on organizational needs and security requirements.

8. **Accountability and Logging:**
   - Every action taken by a user with `ManagerAccess` is logged to maintain a robust audit trail. This includes:
     - The creation of new access roles for other users.
     - Modifications to existing access permissions.
     - Suspensions or revocations of access.
   - These logs are crucial for maintaining transparency and accountability, particularly in complex organizational structures.

#### Example Workflow for ManagerAccess:

1. **Granting Access to an Auditor:**
   - A `ManagerAccess` user identifies the need to provide an external auditor with read-only access to a bank account.
   - They create an `AuditorAccess` entry, specifying the `scope` as read-only and limiting access to account details but not permissions or transaction initiation.
   - This allows the auditor to perform their duties without the risk of unauthorized account changes.

2. **Modifying Access for an Agent:**
   - A company hires a new financial agent, and the `ManagerAccess` user creates an `AgentAccess` entity, granting the agent the ability to perform transactions on behalf of the account holder.
   - The manager specifies that the agent cannot manage access (restricted by scope) but can act in specific agency processes.

3. **Suspending Access:**
   - A manager determines that a user's access needs to be revoked due to a role change or completion of duties.
   - They suspend the `PoAAccess` for a legal representative who no longer needs access to the account.
   - The suspended access prevents the representative from making any further changes or transactions, ensuring security.

#### Role in the Organizational Hierarchy:

- **Delegated Authority:** In most organizational structures, `ManagerAccess` represents a middle-tier authority. They are empowered to manage account access but are still subordinate to the account holder (`HolderAccess`) or a `SeniorManagerAccess` user.
- **Operational Flexibility:** `ManagerAccess` users provide flexibility by enabling dynamic control over access without requiring constant input from senior-level management or the account holder. This delegation of authority is critical for efficient account management, especially in large organizations or teams.

#### Key Considerations for ManagerAccess:

- **Separation of Duties:** It's essential to ensure that `ManagerAccess` does not overlap too much with operational control (e.g., making transactions). Clear separation of duties reduces the risk of internal fraud or unauthorized access.
- **Customization:** The `scope` field allows the manager’s access to be customized based on the specific needs of the account or organization. This flexibility ensures that different managers can be given different levels of responsibility depending on their role.
- **Security:** Managing access is a highly sensitive task, and users with `ManagerAccess` need to operate within defined security policies. Changes to access should always be logged and subject to review, ensuring that permissions are only granted to those who require them.

#### Possible Scenarios of Suspension:

- **Security Incidents:** If a manager’s credentials are compromised, their `ManagerAccess` can be suspended to prevent unauthorized changes to account permissions.
- **Internal Restructuring:** During organizational changes (e.g., departmental shifts, role changes), a manager’s access might be temporarily or permanently suspended until their new role and responsibilities are clarified.
- **Account Holder Override:** If the account holder determines that a manager no longer requires access, they can directly suspend the `ManagerAccess` role, overriding any previously assigned permissions.

#### Key Scenarios for ManagerAccess:

- **Corporate Environments:** A financial manager in a corporation may have `ManagerAccess` to handle day-to-day access control, ensuring that employees in different departments have the correct permissions to view or manage specific sub-accounts.
- **Partnerships:** In joint ventures or partnerships, a manager might be assigned `ManagerAccess` to oversee who from each partner company has access to the shared account, without the manager having the ability to perform transactions themselves.

**Comment by yvanhenang** [comment]
Here's the structure I found before continuing, I wanted it to be validated by the team



```mermaid
erDiagram
    ManagerAccess {
        Long id
        String scope
        double weight
        String status
        Long seniorManagerAccessId
    }

    SeniorManagerAccess {
        Long id
        String name
    }

    HolderAccess {
        Long id
        String name
    }

    AgentAccess {
        Long id
        String name
    }

    AuditorAccess {
        Long id
        String name
    }

    PoAAccess {
        Long id
        String name
    }

    ManagerAccess ||--o{ SeniorManagerAccess : "supervised by"
    ManagerAccess ||--o{ HolderAccess : "granted by"
    ManagerAccess ||--o{ AgentAccess : "manages"
    ManagerAccess ||--o{ AuditorAccess : "manages"
    ManagerAccess ||--o{ PoAAccess : "manages"

```
