### ISSUE TITLE
Define Entity TellerAccess

### ISSUE THREAD

**Issue by francis-pouatcha** [ADORSYS-GIS/ledgers#39]
#### Overview:
`TellerAccess` is a specialized access role designed specifically for bank tellers working within the front office of a financial institution. This role grants the teller the ability to perform routine operational tasks, such as deposits, withdrawals, and account inquiries, on behalf of customers. However, `TellerAccess` does not permit any authority to manage or modify access for other users or make changes to account permissions. The focus of this access is strictly on day-to-day banking transactions that occur in-person at a branch or through a front-office system.

#### Key Characteristics:

1. **Operational Activities Focus:**
   - `TellerAccess` is primarily for activities that happen in a bank’s front office. These include:
     - Processing deposits.
     - Facilitating cash or check withdrawals.
     - Handling cash transactions such as exchanging currency.
     - Answering customer inquiries related to account balances or recent transactions.
   - The role is strictly operational and designed for bank employees who directly interact with customers, processing their requests quickly and efficiently.

2. **No Access Management:**
   - Tellers with `TellerAccess` cannot add, modify, or remove access for other users on the account. This means they cannot grant access to other employees (e.g., managers or agents) or revoke access for existing account holders or representatives.
   - This strict limitation ensures that tellers focus solely on customer-facing transactions, maintaining security and segregation of duties within the bank.

3. **Transaction Limits and Conditions:**
   - `TellerAccess` often comes with predefined transaction limits and conditions based on the bank’s policies. For example:
     - A teller might be allowed to process withdrawals up to a certain amount per day without further approval.
     - For larger transactions, the teller might need authorization from a manager or account holder.
     - The teller may also be restricted from viewing certain sensitive details about the account, such as specific transaction histories or overdraft limits, depending on the access configuration.

4. **Scope of Permissions:**
   - The permissions under `TellerAccess` typically include:
     - **Deposits and Withdrawals:** The teller can facilitate deposits (cash or check) into the customer’s account and process withdrawals based on available funds.
     - **Balance Inquiries:** Tellers can check account balances and provide customers with information about the status of their accounts.
     - **Transaction Inquiries:** They can provide limited details about recent transactions but may be restricted from viewing full transaction histories or large transfers.
     - **Cash Management:** Tellers can manage and record cash-related operations, including exchanging currency or handling cash deposits.
   - These permissions are closely tied to the teller’s role of facilitating front-office interactions, and the scope can be adjusted based on the bank’s policies.

5. **Weight:**
   - The `weight` of `TellerAccess` is typically lower than other roles like `ManagerAccess` or `SeniorManagerAccess`. For example:
     - A `weight` of **0.2** or **0.3** would represent limited authority, sufficient for conducting front-office activities but lacking in permissions for decision-making or access management.
     - This weight reflects the teller’s narrow focus on customer-facing operations and the lack of higher-level privileges like access control.

6. **Status:**
   - The status of `TellerAccess` can change based on operational needs or restrictions imposed by the bank:
     - **Active:** The teller is authorized to conduct day-to-day transactions for customers.
     - **Restricted:** The teller’s access may be temporarily limited (e.g., to perform only inquiries but not transactions) during certain conditions, such as branch audits or investigations.
     - **Suspended:** The teller’s access is revoked, either due to policy changes, disciplinary actions, or internal security concerns.
   - The dynamic status of `TellerAccess` ensures that the bank can regulate teller activities in response to operational or security needs.

7. **Logging and Accountability:**
   - All actions taken by the teller using `TellerAccess` are logged and auditable to ensure transparency. These logs include:
     - Deposit and withdrawal transactions.
     - Customer inquiries and account status checks.
     - Any anomalies, such as failed transactions or authorization requests for larger amounts.
   - This audit trail helps prevent fraud and ensures that every transaction can be traced back to the teller who performed it.

8. **Conditions and Limits:**
   - Tellers often operate under predefined conditions or limits, such as:
     - **Daily Transaction Limits:** A maximum amount they can process for withdrawals or deposits without manager approval.
     - **Currency Exchange Caps:** Restrictions on the amount of foreign currency they can exchange for a customer without additional oversight.
     - **Customer Verification Procedures:** Tellers must follow bank protocols to verify customer identity before processing transactions, ensuring security and compliance with regulations.

#### Example Workflow for TellerAccess:

1. **Processing a Deposit:**
   - A customer walks into a bank and provides the teller with cash to deposit into their account.
   - The teller uses `TellerAccess` to verify the account balance, ensure the account is active, and process the deposit, updating the account balance accordingly.
   - The transaction is logged in the system under the teller’s ID, providing an audit trail of the deposit.

2. **Facilitating a Withdrawal:**
   - A customer requests to withdraw cash from their account. The teller uses `TellerAccess` to check the available balance and processes the withdrawal.
   - If the withdrawal exceeds a certain limit, the teller might require approval from a manager before completing the transaction.
   - Once approved, the teller hands over the cash to the customer and records the transaction in the system.

3. **Currency Exchange:**
   - A customer wishes to exchange foreign currency. The teller, using `TellerAccess`, checks the current exchange rates and processes the currency exchange within the limits set by the bank.
   - If the amount is larger than the teller’s allowed limit, they seek approval from a higher authority, such as a branch manager.

#### Key Considerations for TellerAccess:

- **Security and Compliance:** Tellers must follow strict security protocols to verify customer identity and ensure that transactions are properly authorized. This helps prevent fraud and unauthorized access to customer accounts.
- **Segregation of Duties:** By restricting tellers from managing access or making changes to account permissions, banks ensure that operational and governance duties remain separate. This separation of powers helps maintain internal security.
- **Clear Scope Definition:** The scope of `TellerAccess` should be clearly defined to match the teller’s role, preventing any overreach or misuse of authority. It should be limited to customer-facing operations and exclude any access to sensitive internal data or account management functions.

#### Scenarios for Suspension or Restriction:

- **Branch Audits or Investigations:** During an internal audit or investigation, a teller’s access might be restricted to ensure no new transactions are processed until the audit is complete.
- **Suspicion of Misconduct:** If there are suspicions of fraudulent activity, a teller’s access might be temporarily suspended pending an investigation.
- **Role Changes or Transfers:** If a teller is transferred to a new role within the bank or promoted, their `TellerAccess` might be revoked or updated to reflect their new responsibilities.

#### Example Use Cases:

- **Daily Banking Transactions:** Tellers use `TellerAccess` every day to assist customers with deposits, withdrawals, and basic account inquiries. This access allows them to serve customers efficiently without needing access to higher-level account controls.
- **Handling Routine Customer Requests:** When customers need to update personal details, inquire about account balances, or perform other routine tasks, tellers use their access to facilitate these requests quickly and accurately.
- **Branch Operations:** In branch environments, tellers act as the frontline staff who use `TellerAccess` to manage customer transactions, making it a crucial role for the smooth operation of physical bank locations.

**Comment by yvanhenang** [comment]
Thank you for the description sir
